---

name: Synthesis

on: [push, pull_request]

env:
  PY_COLORS: 1

jobs:
  yosys:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Get submodules
        run: git submodule update --init --recursive
      - name: Get Docker image
        run: docker pull ghdl/synth:beta
      - name: Run Yosys
        run: misc/run_synth.sh
